import java.util.*;
import java.util.HashMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class FortuneTeller extends javax.swing.JFrame {

    /**
     * Creates new form FortuneTeller
     */
    public FortuneTeller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        calculation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        second = new javax.swing.JTextField();
        third = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstname1 = new javax.swing.JTextField();
        secname1 = new javax.swing.JTextField();
        thirdname1 = new javax.swing.JTextField();
        firstname2 = new javax.swing.JTextField();
        secname2 = new javax.swing.JTextField();
        thirdname2 = new javax.swing.JTextField();
        connectionMode = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        connectionCalc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        connectionOutput = new javax.swing.JTextArea();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        output.setColumns(20);
        output.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        calculation.setFont(new java.awt.Font("標楷體", 0, 18)); // NOI18N
        calculation.setText("開始計算");
        calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        jLabel1.setText("請輸入名字筆畫:");

        first.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        second.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N

        third.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        jLabel2.setText("計算結果:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calculation, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(third, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(226, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(second)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(third)))
                .addGap(6, 6, 6)
                .addComponent(calculation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("單人計算", jPanel1);

        jLabel3.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        jLabel3.setText("選擇模式:");

        jLabel4.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        jLabel4.setText("乙方筆畫:");

        firstname1.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        secname1.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        thirdname1.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        firstname2.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        secname2.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        thirdname2.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N

        connectionMode.setFont(new java.awt.Font("標楷體", 0, 14)); // NOI18N
        connectionMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "感情來電", "貴小人" }));

        jLabel5.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        jLabel5.setText("甲方筆畫: ");

        connectionCalc.setFont(new java.awt.Font("標楷體", 0, 24)); // NOI18N
        connectionCalc.setText("開始計算");
        connectionCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionCalcActionPerformed(evt);
            }
        });

        connectionOutput.setColumns(20);
        connectionOutput.setRows(5);
        jScrollPane2.setViewportView(connectionOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstname1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(firstname2))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secname1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secname2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(thirdname2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdname1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(166, 166, 166)
                                        .addComponent(connectionCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(connectionMode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 185, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(763, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secname1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdname1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstname2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secname2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdname2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectionMode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(connectionCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("感情來電& 貴小人&財官印", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationActionPerformed
        // TODO add your handling code here:
        int first_num = Integer.parseInt(first.getText());
        int sec_num = Integer.parseInt(second.getText());
        int third_num = Integer.parseInt(third.getText());
        NameSeeker name = new NameSeeker(first_num, sec_num, third_num);
        Attribute attribute = new Attribute(name);
        HeavenlyStems heavenly_stems = new HeavenlyStems(name);
        TerrestrialBranch terrestrial = new TerrestrialBranch(name);
        Set<String> nature = AttributeCalculator.nature_fortune(attribute);
        Set<String> absent = AttributeCalculator.abs_fortune(nature);
        HashMap<String, String> nature_fortune = SpecificNumber.natureFortune(name);
        output.append("天格: " + name.getSkyBlock()+ "\t" + attribute.get_sky_att() + "\t" + heavenly_stems.get_sky_stem() + "\t" + terrestrial.get_sky_branch()+"\n");
        output.append("人格: " + name.getPeopleBlock()+ "\t" + attribute.get_people_att() + "\t" + heavenly_stems.get_people_stem() + "\t" + terrestrial.get_people_branch()+"\n");
        output.append("地格: " + name.getGroundBlock()+ "\t" + attribute.get_ground_att() + "\t" + heavenly_stems.get_ground_stem() + "\t" + terrestrial.get_ground_branch()+"\n");
        output.append("外格: " + name.getOutBlock()+ "\t" + attribute.get_out_att() + "\t" + heavenly_stems.get_out_stem() + "\t" + terrestrial.get_out_branch()+"\n");
        output.append("總格: " + name.getTotalBlock()+ "\t" + attribute.get_total_att() + "\t" + heavenly_stems.get_total_stem() + "\t" + terrestrial.get_total_branch()+"\n");
        output.append("財官印: "+ nature.toString()+"\n");
        output.append("破: "+absent.toString()+"\n");
        output.append("靈數\n");
        for(Map.Entry<String, String> set: nature_fortune.entrySet()){
        output.append(set.getKey() + ":  " + set.getValue()+"\n");
        }
    }//GEN-LAST:event_calculationActionPerformed

    private void connectionCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionCalcActionPerformed
        // TODO add your handling code here:
        int first_num1 = Integer.parseInt(firstname1.getText());
        int sec_num1 = Integer.parseInt(secname1.getText());
        int third_num1 = Integer.parseInt(thirdname1.getText());
        int first_num2 = Integer.parseInt(firstname2.getText());
        int sec_num2 = Integer.parseInt(secname2.getText());
        int third_num2 = Integer.parseInt(thirdname2.getText());
        NameSeeker name1 = new NameSeeker(first_num1, sec_num1, third_num1);
        NameSeeker name2 = new NameSeeker(first_num2, sec_num2, third_num2);
        Attribute attribute1 = new Attribute(name1);
        Attribute attribute2 = new Attribute(name2);
        HashMap<String, String> connection = new HashMap<String, String>();
        if(connectionMode.getSelectedItem().toString() == "感情來電"){
          connection = AttributeCalculator.lover_match(attribute1, attribute2);
          for(Map.Entry<String, String>  i : connection.entrySet()){
           connectionOutput.append(i.getKey() + "  "+ i.getValue() +"\n");
          }
        }if(connectionMode.getSelectedItem().toString() == "貴小人"){
             connection = AttributeCalculator.noble_person(name1, name2);
          for(Map.Entry<String, String>  i : connection.entrySet()){
             connectionOutput.append(i.getKey() + "  "+ i.getValue()+"\n");
          }
        }

        
    }//GEN-LAST:event_connectionCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FortuneTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FortuneTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FortuneTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FortuneTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FortuneTeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculation;
    private javax.swing.JButton connectionCalc;
    private javax.swing.JComboBox<String> connectionMode;
    private javax.swing.JTextArea connectionOutput;
    private javax.swing.JTextField first;
    private javax.swing.JTextField firstname1;
    private javax.swing.JTextField firstname2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField secname1;
    private javax.swing.JTextField secname2;
    private javax.swing.JTextField second;
    private javax.swing.JTextField third;
    private javax.swing.JTextField thirdname1;
    private javax.swing.JTextField thirdname2;
    // End of variables declaration//GEN-END:variables
}
